agent_name: counter_client
author: valory
version: 0.1.0
description: The ABCI Counter example as an AEA
license: Apache-2.0
aea_version: '>=1.0.0, <2.0.0'
fingerprint: {}
fingerprint_ignore_patterns: []
connections:
- fetchai/http_client:0.22.0
contracts: []
protocols:
- fetchai/default:1.0.0
- fetchai/http:1.0.0
- fetchai/signing:1.0.0
- fetchai/state_update:1.0.0
skills:
- valory/counter_client:0.1.0
default_ledger: fetchai
required_ledgers:
- fetchai
default_routing: {}
connection_private_key_paths: {}
private_key_paths:
  fetchai: fetchai_private_key.txt
logging_config:
  disable_existing_loggers: false
  version: 1
dependencies:
  aea-ledger-fetchai: {}
default_connection: null
