name: register_reset
author: valory
version: 0.1.0
agent: valory/register_reset:0.1.0:bafybeiaymbo2s7qzmque5vfzh4pv76kieutb4hlmo75xs5a3g6xgkpgnpm
network: hardhat
number_of_agents: 4
description: Test and debug tendermint reset mechanism.
aea_version: '>=1.0.0, <2.0.0'
license: Apache-2.0
fingerprint:
  README.md: bafybeiae4sog7e3hyjdujzp5qr2g3auobmqswqnaczh2zhlphuojnd2g6u
fingerprint_ignore_patterns: []
