agent_name: counter
author: valory
version: 0.1.0
description: The ABCI Counter example as an AEA
license: Apache-2.0
aea_version: '>=1.0.0, <2.0.0'
fingerprint:
  README.md: QmSbdQDou9tgrq1uXdAGQ9o3LV6N3ZVNKXpzSRFkrq7HJY
fingerprint_ignore_patterns: []
connections:
- valory/abci:0.1.0:QmPPZyzTNTGyvFsyZmBXkJfkKjuZi1KJjCeMmZvdsGA6U7
contracts: []
protocols:
- open_aea/signing:1.0.0:QmemReviejNSLrwWqENKL76AtoK17eG8TBbWjpwUT7L3UA
- valory/abci:0.1.0:QmZBJS6SEKyDU1QYU3LVU6VTFqpbSkjPgLkwzefK2SVSvq
skills:
- valory/abstract_abci:0.1.0:QmcG3ejvMG6TN8yVwpGm2pLaDZQyhodZgwFTCNgFiP2KE4
- valory/counter:0.1.0:Qmeii3TAWuGaqyEnuTmoL99BqyQKttcQcaPNycxoi5BZjo
default_ledger: ethereum
required_ledgers:
- ethereum
default_routing: {}
connection_private_key_paths: {}
private_key_paths: {}
logging_config:
  disable_existing_loggers: false
  version: 1
dependencies:
  open-aea-ledger-ethereum: {}
default_connection: null
---
public_id: valory/abci:0.1.0
type: connection
config:
  target_skill_id: valory/counter:0.1.0
