name: counter
author: valory
version: 0.1.0
description: A set of agents incrementing a counter
aea_version: '>=1.0.0, <2.0.0'
license: Apache-2.0
fingerprint:
  README.md: QmVnym7UFqPzwQrFpZZ5hC6V9gAWbttNU2aJmv9r4gYog5
fingerprint_ignore_patterns: []
number_of_agents: 1
agent: valory/counter:0.1.0:QmR61Vz7s1WdBeSa8oJLbBLUV22z55Hb1SHdcsDLZh3Hrb
network: hardhat
