name: oracle_goerli
author: valory
version: 0.1.0
description: A set of agents implementing a price oracle
aea_version: '>=1.0.0, <2.0.0'
license: Apache-2.0
fingerprint:
  README.md: bafybeifpb54id7wln2ayku65s3qmih3aljf23rfpsggjwuzc7cnkfroi7y
fingerprint_ignore_patterns: []
agent: valory/oracle:0.1.0:bafybeig7j64xv36he4ua3szdozrfr7c2w5sbqb6znpl32wamg5mggadzxe
network:
  id: goerli
  address: https://goerli.infura.io/v3/7afbd9ac9d0345578d9ccd6594300acd
  chain_id: 5
  poa_chain: true
  default_gas_price_strategy: eip1559
number_of_agents: 4
---
setup_args:
  args: &id001
    setup:
      safe_contract_address:
      - '0x623cE6087190B53520f00609d41d79e5B71B881F'
      oracle_contract_address: 
      - '0xA2b06beb69b5e454759976ABa7555e2639c0522f'
    max_healthcheck: 43200
    broadcast_to_server: true
valory_monitoring_backend:
  args: &id002
    url: https://staging.oracle-server.autonolas.tech/deposit
public_id: valory/oracle_abci:0.1.0
type: skill
models:
  0:
  - price_api:
      args:
        url: https://api.coingecko.com/api/v3/simple/price
        api_id: coingecko
        parameters:
        - - ids
          - bitcoin
        - - vs_currencies
          - usd
        response_key: bitcoin:usd
        headers: null
  - randomness_api:
      args:
        url: https://drand.cloudflare.com/public/latest
        api_id: cloudflare
  - params:
      args: *id001
  - server_api:
      args: *id002
  1:
  - price_api:
      args:
        url: https://ftx.com/api/markets/BTC/USD
        api_id: ftx
        response_key: result:last
        headers: null
        parameters: null
  - randomness_api:
      args:
        url: https://api.drand.sh/public/latest
        api_id: protocollabs1
  - params:
      args: *id001
  - server_api:
      args: *id002
  2:
  - price_api:
      args:
        url: https://api.coinbase.com/v2/prices/BTC-USD/buy
        api_id: coinbase
        response_key: data:amount
        headers: null
        parameters: null
  - randomness_api:
      args:
        url: https://api2.drand.sh/public/latest
        api_id: protocollabs2
  - params:
      args: *id001
  - server_api:
      args: *id002
  3:
  - price_api:
      args:
        url: https://api.binance.com/api/v3/ticker/price
        api_id: binance
        parameters:
        - - symbol
          - BTCUSDT
        response_key: price
        headers: null
  - randomness_api:
      args:
        url: https://api3.drand.sh/public/latest
        api_id: protocollabs2
  - params:
      args: *id001
  - server_api:
      args: *id002
